name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Cache
      uses: actions/cache@v2.1.3
      with:
    # A list of files, directories, and wildcard patterns to cache and restore
        path: /.nuget/packages
        key: ${{ runner.os }}-nuget
    - shell: bash
      run: where python
    - shell: bash
      run: where pip
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - shell: bash
      env: 
        SECRET:  ${{ secrets.SECRET }}
      run: dotnet run --no-build --configuration Release
