name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    # Works without it
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        

    - name: Cache
      uses: actions/cache@v2.1.3
      with:
    # A list of files, directories, and wildcard patterns to cache and restore
        path: /.nuget/packages
        key: ${{ runner.os }}-nuget
    - shell: bash
      run: which python
    - shell: bash
      run: which pip
    - name: Restore dependencies
      run: dotnet restore
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-  
    - name: Pip install
      run: pip install -I matplotlib
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - shell: bash
      env: 
        SECRET:  ${{ secrets.SECRET }}
      run: dotnet run --no-build --configuration Release
      
    - shell: bash
      env:
        PYTHON_PATH: $pythonLocation
      run: python
